baseURL = "https://gilded-pasca-5bc1eb.netlify.app/"
languageCode = "de-de"
title = "Polithea – Theater der Unterdrückten Osnabrück"
theme = "kaldi"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
logo = "/images/logo.png"
phone = ""
email = "act@polithea.de"
images = ["img/logo.png"]

[menu]

[[menu.main]]
name = "Über Uns"
url = "/about"
weight = 1

[[menu.main]]
name = "Unsere Arbeit"
url = "/products"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3